// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Validates and opens a local repository, returning its canonical identity. */
	openRepository: (path: string) => typedError<RepositoryInfo, AppError>(__TAURI_INVOKE("open_repository", { path })),
	/**  Checks a candidate working-tree root without changing application selection. */
	validateRepository: (path: string) => typedError<RepositoryInfo, AppError>(__TAURI_INVOKE("validate_repository", { path })),
	/**
	 *  The repository named on the command line, if the application was launched
	 *  with one.
	 *
	 *  `gitcanvas /path/to/repo` is what a terminal user expects of a Git client,
	 *  and it is also what lets the end-to-end suite open a repository without a
	 *  native file dialog.
	 *
	 *  Every argument is scanned rather than only the first: a launcher may put its
	 *  own flags ahead of the user's path, which is exactly what the WebDriver
	 *  harness does. The first argument that both looks like a path and validates
	 *  as a repository wins; an argument that is not one is skipped rather than
	 *  reported, because it probably belongs to the runtime.
	 *
	 *  `GITCANVAS_REPOSITORY` does the same thing for environments where passing
	 *  arguments is awkward.
	 */
	getStartupRepository: () => typedError<{
	/**  Canonical absolute repository path. */
	path: string,
	/**  Repository directory name for display. */
	name: string,
} | null, AppError>(__TAURI_INVOKE("get_startup_repository")),
	/**  Reads a bounded history page using the selected repository's canonical path. */
	getCommits: (path: string, request: HistoryRequest) => typedError<HistoryPage, AppError>(__TAURI_INVOKE("get_commits", { path, request })),
	/**  Lists local and remote branches and identifies the current branch. */
	getBranches: (path: string) => typedError<BranchInfo[], AppError>(__TAURI_INVOKE("get_branches", { path })),
	/**  Lists tags, peeling annotated tags to commits when applicable. */
	getTags: (path: string) => typedError<TagInfo[], AppError>(__TAURI_INVOKE("get_tags", { path })),
	/**
	 *  Reads a commit's changes against its first parent.
	 *
	 *  `request.expand_path` opts one file out of the size guard, which is how the
	 *  interface loads a large diff only when the user asks for it.
	 */
	getCommitDiff: (path: string, request: DiffRequest) => typedError<CommitDiff, AppError>(__TAURI_INVOKE("get_commit_diff", { path, request })),
	/**
	 *  Reads a file's full contents as it stands at a commit.
	 *
	 *  Complements the diff: a change only shows what moved, and reading the file
	 *  around it is often what answers the question.
	 */
	getFileContent: (path: string, request: FileContentRequest) => typedError<FileContent, AppError>(__TAURI_INVOKE("get_file_content", { path, request })),
	/**  Reads one bounded page of direct children from a commit directory. */
	getCommitTreePage: (path: string, request: CommitTreeRequest) => typedError<CommitTreePage, AppError>(__TAURI_INVOKE("get_commit_tree_page", { path, request })),
	/**  Reads both local change sets with one repository revision. */
	getWorktreeSnapshot: (path: string, request: WorktreeSnapshotRequest) => typedError<WorktreeSnapshot, AppError>(__TAURI_INVOKE("get_worktree_snapshot", { path, request })),
	/**  Reads one staged or unstaged file diff on demand. */
	getWorktreeFileDiff: (path: string, request: WorktreeFileDiffRequest) => typedError<WorktreeFileDiff, AppError>(__TAURI_INVOKE("get_worktree_file_diff", { path, request })),
	/**  Reads a staged file from the index or an unstaged file from disk. */
	getWorktreeFileContent: (path: string, request: WorktreeFileContentRequest) => typedError<WorktreeFileContent, AppError>(__TAURI_INVOKE("get_worktree_file_content", { path, request })),
	/**  Reads a cheap revision used when filesystem events are unavailable. */
	getWorktreeFingerprint: (path: string) => typedError<WorktreeFingerprint, AppError>(__TAURI_INVOKE("get_worktree_fingerprint", { path })),
	/**  Stores a personal access token in the OS keychain. */
	storeGithubToken: (token: string) => typedError<GitHubAccount, AppError>(__TAURI_INVOKE("store_github_token", { token })),
	/**  Reports whether a token is stored, without revealing it. */
	hasGithubToken: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_github_token")),
	/**  Removes the stored token. */
	forgetGithubToken: () => typedError<null, AppError>(__TAURI_INVOKE("forget_github_token")),
	/**  Lists the repositories the stored token can reach. */
	listGithubRepositories: () => typedError<GitHubRepositoryList, AppError>(__TAURI_INVOKE("list_github_repositories")),
	/**  Clones a repository into the application cache, emitting progress as it goes. */
	cloneGithubRepository: (cloneUrl: string, fullName: string, activeRepositoryPath: string | null) => typedError<ClonedRepository, AppError>(__TAURI_INVOKE("clone_github_repository", { cloneUrl, fullName, activeRepositoryPath })),
	/**  Reports what the clone cache holds and the limits it is held to. */
	getCloneCacheStatus: () => typedError<CacheStatus, AppError>(__TAURI_INVOKE("get_clone_cache_status")),
	/**  Checks out a local branch, refusing by default when work would be lost. */
	checkoutBranch: (path: string, branch: string, force: boolean) => typedError<CheckoutOutcome, AppError>(__TAURI_INVOKE("checkout_branch", { path, branch, force })),
	/**  Fetches and fast-forwards the current branch, reporting anything else. */
	pullFastForward: (path: string) => typedError<PullOutcome, AppError>(__TAURI_INVOKE("pull_fast_forward", { path })),
	/**  Pushes the current branch to its remote. */
	pushCurrentBranch: (path: string) => typedError<PushOutcome, AppError>(__TAURI_INVOKE("push_current_branch", { path })),
	/**
	 *  Starts watching a repository, replacing any previous watch.
	 *
	 *  Idempotent from the interface's point of view: calling it again for the
	 *  same repository simply re-establishes the watch.
	 */
	watchRepository: (request: WatchRequest) => typedError<null, AppError>(__TAURI_INVOKE("watch_repository", { request })),
	/**  Stops watching, if anything was being watched. */
	unwatchRepository: (generation: number) => typedError<null, AppError>(__TAURI_INVOKE("unwatch_repository", { generation })),
};

/** Events */
export const events = {
	cloneProgressEvent: makeEvent<CloneProgressEvent>("clone-progress-event"),
	repositoryChangedEvent: makeEvent<RepositoryChangedEvent>("repository-changed-event"),
};

/* Types */
/**  A domain failure, never a raw library error or a panic. */
export type AppError =
/**  The supplied path does not identify a supported working repository. */
{ kind: "InvalidRepository"; message: string } |
/**  A filesystem operation failed. */
{ kind: "Io"; message: string } |
/**  libgit2 could not complete an operation. */
{ kind: "Git"; message: string } |
/**  Credentials were missing or rejected by a remote service. */
{ kind: "Auth"; message: string } |
/**  A remote service could not be reached or did not respond in time. */
{ kind: "Network"; message: string } |
/**  The requested operation conflicts with the repository or remote state. */
{ kind: "Conflict"; message: string } |
/**  A request violates the public contract. */
{ kind: "InvalidInput"; message: string } |
/**  A requested file would resolve outside the selected repository. */
{ kind: "PathOutsideRepository"; message: string } |
/**  The working tree changed while a local file was being read. */
{ kind: "WorktreeChanged"; message: string } |
/**  The requested local file cannot be represented by the selected source. */
{ kind: "WorktreeFileUnavailable"; message: string } |
/**  The operation would exceed an explicit resource budget. */
{ kind: "ResourceLimitExceeded"; message: string } |
/**  The filesystem watcher is not available for this repository. */
{ kind: "WatchDegraded"; message: string } |
/**  The history represented by a pagination cursor is no longer available. */
{ kind: "StaleCursor"; message: string } |
/**
 *  The process ran out of file descriptors. Transient: retrying after other
 *  work has released its handles usually succeeds.
 */
{ kind: "ResourceExhausted"; message: string } |
/**  Background work could not complete. */
{ kind: "Internal"; message: string };

/**  A branch uses its full ref name as identity; short names are display only. */
export type BranchInfo = {
	/**  Short branch name for display. */
	name: string,
	/**  Full ref name used as branch identity. */
	full_name: string,
	/**  Commit id at the branch tip. */
	target: string,
	/**  Whether this branch belongs to a remote. */
	is_remote: boolean,
	/**  Whether this is the currently checked-out branch. */
	is_head: boolean,
	/**  Whether this ref is symbolic instead of direct. */
	is_symbolic: boolean,
};

/**  One cached clone. */
export type CacheEntry = {
	/**  Absolute path to the cached repository. */
	path: string,
	/**  Stable cache entry name. */
	name: string,
	/**
	 *  Size in bytes, as a decimal string.
	 *
	 *  A directory can exceed what a JavaScript number represents exactly, and
	 *  specta refuses to export 64-bit integers for that reason. The same
	 *  convention as commit timestamps: cross the boundary as text, parse on
	 *  the far side.
	 */
	bytes: string,
	/**  Unix seconds of the most recent access, as a string for range safety. */
	last_used: string,
};

/**  What the cache currently holds. */
export type CacheStatus = {
	/**  Cached clones currently retained. */
	entries: CacheEntry[],
	/**  Total size in bytes, as a decimal string. See [`CacheEntry::bytes`]. */
	total_bytes: string,
	/**  Maximum number of clones retained. */
	max_repositories: number,
	/**  Limit in bytes, as a decimal string. See [`CacheEntry::bytes`]. */
	max_total_bytes: string,
};

/**
 *  The outcome of a checkout attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type CheckoutOutcome =
/**  The branch is now checked out. */
{ kind: "Switched";
/**  Name of the branch now checked out. */
branch: string } |
/**  Refused: these changes would have been lost. */
{ kind: "Blocked";
/**  Local paths that prevent a safe checkout. */
conflicts: DirtyPath[] };

/**  Progress for an in-flight clone, emitted as it advances. */
export type CloneProgressEvent = {
	full_name: string,
	received_objects: number,
	total_objects: number,
	received_bytes: string,
};

/**  Where a clone landed. */
export type ClonedRepository = {
	/**  Absolute path where the new clone was created. */
	path: string,
	/**  Owner and repository name separated by `/`. */
	full_name: string,
};

/**  A commit's changes against its first parent. */
export type CommitDiff = {
	/**  Commit whose changes are described. */
	commit_id: string,
	/**  The parent compared against; absent for a root commit. */
	parent_id: string | null,
	/**  Changed files, with a patch only for the requested path. */
	files: FileDiff[],
	/**  Total inserted lines across all changed files. */
	insertions: number,
	/**  Total deleted lines across all changed files. */
	deletions: number,
	/**  True when this commit has more than one parent, so the diff covers one side. */
	is_merge: boolean,
};

/**  One commit in the graph. Times are decimal Unix seconds, preserving Git's full integer range. */
export type CommitInfo = {
	/**  Full object id of the commit. */
	id: string,
	/**  Parent commit ids in their recorded order. */
	parents: string[],
	/**  First line of the commit message. */
	summary: string,
	/**  Full commit message. */
	message: string,
	/**  Author display name. */
	author_name: string,
	/**  Author email address. */
	author_email: string,
	/**  Author timestamp in Unix seconds, represented as decimal text. */
	author_time: string,
	/**  Committer timestamp in Unix seconds, represented as decimal text. */
	commit_time: string,
};

/**  A direct child in a commit tree. Directories are loaded on demand by the UI. */
export type CommitTreeEntry = {
	/**  Display name of this direct child. */
	name: string,
	/**  Repository-relative path, always separated with `/`. */
	path: string,
	/**  Whether this child is a directory, file, or submodule. */
	kind: CommitTreeEntryKind,
};

/**  Git object types that can occur in a tree and have distinct UI behavior. */
export type CommitTreeEntryKind =
/**  A tree that can be expanded to list its direct children. */
"Directory" |
/**  A blob leaf. */
"File" |
/**  A gitlink to another repository. */
"Submodule";

/**  A bounded page of direct children from a commit directory. */
export type CommitTreePage = {
	/**  Commit whose tree is being listed. */
	commit_id: string,
	/**  Repository-relative directory path; `None` denotes the root. */
	directory_path: string | null,
	/**  Direct children returned for this page. */
	entries: CommitTreeEntry[],
	/**  Offset for the next page, absent when this directory is exhausted. */
	next_offset: number | null,
};

/**  Identifies one immutable commit directory and the next direct-child offset. */
export type CommitTreeRequest = {
	/**  Commit whose tree is being listed. */
	commit_id: string,
	/**  `None` selects the root. Non-root paths must be canonical Git paths. */
	directory_path: string | null,
	/**  Offset into the directory's sorted direct children. */
	offset: number,
};

/**  Why a file has no renderable hunks. */
export type DiffOmission =
/**  libgit2 reports the content as binary; there is no line diff to show. */
"Binary" |
/**  The change is larger than `LARGE_DIFF_LINE_LIMIT` and was not requested. */
"TooLarge";

/**  Bounds and selects the patch returned with commit change summaries. */
export type DiffRequest = {
	/**  Commit whose changes are requested. */
	commit_id: string,
	/**  Changed path whose patch is requested; other files are summaries only. */
	file_path: string | null,
	/**  Path whose ordinary line and byte thresholds are bypassed, up to the hard cap. */
	expand_path: string | null,
};

/**  A path that would be lost or overwritten by an operation. */
export type DirtyPath = {
	/**  Repository-relative path that would be discarded or overwritten. */
	path: string,
	/**  True when the change is staged, false when it is only in the worktree. */
	staged: boolean,
};

/**  How a path changed between two trees. */
export type FileChange =
/**  A path was added. */
"Added" |
/**  An existing path changed. */
"Modified" |
/**  A path was removed. */
"Deleted" |
/**  Git detected that a path moved. */
"Renamed" |
/**  Git detected a copy from an existing path. */
"Copied" |
/**  A path's object type changed. */
"TypeChanged" |
/**  Another change kind not represented above. */
"Other";

/**  A file as it stands at one commit. */
export type FileContent = {
	/**  Repository-relative path of the file. */
	path: string,
	/**  Commit that supplies the file contents. */
	commit_id: string,
	/**  Total lines, available even when the text itself is withheld. */
	lines: number,
	/**
	 *  Size in bytes, as a decimal string; a blob can exceed a JavaScript
	 *  integer, and specta refuses to export 64-bit numbers.
	 */
	bytes: string,
	/**  Why `text` was withheld, if it was not returned. */
	omitted: DiffOmission | null,
	/**  The text, or `None` whenever `omitted` is set. */
	text: string | null,
};

/**  What the caller wants read. */
export type FileContentRequest = {
	/**  Commit from which to read the file. */
	commit_id: string,
	/**  Repository-relative path to read. */
	path: string,
	/**  Return the text even if it exceeds the line budget. */
	expand: boolean,
};

/**
 *  One file in a commit's diff.
 *
 *  `patch` is `None` whenever `omitted` is set, so the two can never disagree
 *  about whether there is something to render.
 */
export type FileDiff = {
	/**  Current repository-relative path. */
	path: string,
	/**  Previous path for renames and copies. */
	old_path: string | null,
	/**  Kind of change represented by this file entry. */
	change: FileChange,
	/**  Number of inserted lines. */
	insertions: number,
	/**  Number of deleted lines. */
	deletions: number,
	/**  Why the patch is omitted, if applicable. */
	omitted: DiffOmission | null,
	/**  Unified patch text for this file alone, ready for a diff renderer. */
	patch: string | null,
};

/**  File metadata used by large listings before a patch is requested. */
export type FileDiffSummary = {
	/**  Current repository-relative path. */
	path: string,
	/**  Previous path for renames and copies. */
	old_path: string | null,
	/**  Kind of change represented by this file entry. */
	change: FileChange,
	/**  Number of inserted lines. */
	insertions: number,
	/**  Number of deleted lines. */
	deletions: number,
	/**  Why the patch is omitted, if applicable. */
	omitted: DiffOmission | null,
};

/**  The authenticated account. */
export type GitHubAccount = {
	/**  GitHub account login. */
	login: string,
	/**  Display name supplied by GitHub, if set. */
	name: string | null,
};

/**  A repository the token can reach. */
export type GitHubRepository = {
	/**  Owner and repository name separated by `/`. */
	full_name: string,
	/**  HTTPS URL used to clone this repository. */
	clone_url: string,
	/**  Whether the repository is private. */
	private: boolean,
	/**  Name of the repository's default branch. */
	default_branch: string,
	/**  Repository description, if supplied. */
	description: string | null,
};

/**  The bounded repository listing and whether more repositories were available. */
export type GitHubRepositoryList = {
	/**  Repositories returned within the configured page limit. */
	repositories: GitHubRepository[],
	/**  Whether additional repositories were omitted by the result limit. */
	truncated: boolean,
};

/**  A bounded page and the information needed to resume its exact traversal. */
export type HistoryPage = {
	/**  Commits returned in topological history order. */
	commits: CommitInfo[],
	/**  Cursor for the next page, or `None` when traversal is complete. */
	next_cursor: string | null,
	/**  Roots required to resume the history walk. */
	roots: string[],
};

/**  Request for a page. Continuations carry the prior page's immutable walk roots. */
export type HistoryRequest = {
	/**  Maximum number of commits requested for this page. */
	limit: number,
	/**  Opaque cursor returned by the preceding page, if any. */
	cursor: string | null,
	/**  Walk roots to use when resuming a paged history traversal. */
	roots: string[] | null,
};

/**
 *  The outcome of a pull attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type PullOutcome =
/**  Already up to date; nothing was fetched that changes the branch. */
{ kind: "UpToDate" } |
/**  Fast-forwarded to the remote tip. */
{ kind: "FastForwarded";
/**  Number of commits added by the fast-forward. */
commits: number;
/**  Commit id at the new branch tip. */
to: string } |
/**  Refused: the histories diverged and a real merge would be required. */
{ kind: "DivergedRequiresMerge";
/**  Local branch tip commit id. */
local: string;
/**  Upstream branch tip commit id. */
remote: string } |
/**  The branch has no upstream to pull from. */
{ kind: "NoUpstream" };

/**
 *  The outcome of a push attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type PushOutcome =
/**  Successfully pushed the checked-out branch. */
{ kind: "Pushed";
/**  Name of the branch sent. */
branch: string;
/**  Name of the remote that received it. */
remote: string } |
/**  Refused: the remote has commits the local branch does not. */
{ kind: "RejectedNonFastForward";
/**  Name of the branch the remote rejected. */
branch: string };

export type RepositoryChangedEvent = {
	path: string,
	generation: number,
	kind: RepositoryChangedKind,
};

/**  Announces a scoped change in the generation currently shown by the window. */
export type RepositoryChangedKind = "Metadata" | "Worktree" | { Degraded: {
	message: string,
} };

/**  Displayable repository identity, safe to send across IPC. */
export type RepositoryInfo = {
	/**  Canonical absolute repository path. */
	path: string,
	/**  Repository directory name for display. */
	name: string,
};

/**  A tag may refer to any Git object, so a commit target is explicitly optional. */
export type TagInfo = {
	/**  Tag name for display. */
	name: string,
	/**  Object id directly referenced by the tag. */
	target: string,
	/**  Resolved commit id, if the target peels to a commit. */
	commit_id: string | null,
	/**  Whether the tag points to an annotated tag object. */
	is_annotated: boolean,
};

export type WatchRequest = {
	path: string,
	generation: number,
};

/**
 *  A bounded page of local file summaries.
 *
 *  `next_cursor` is `"<revision>:<offset>"`: the position is bound to the listing
 *  it was read from and is refused as stale once the changes have moved on.
 */
export type WorktreeDiffPage = {
	/**  Side of the working tree represented by this page. */
	side: WorktreeSide,
	/**  Revision token shared by the snapshot and its pages. */
	revision: string,
	/**  Changed files included in this page. */
	files: FileDiffSummary[],
	/**  Total number of changed files on this side. */
	total_files: number,
	/**  Cursor for the next page, or `None` when complete. */
	next_cursor: string | null,
	/**  Total inserted lines across this side. */
	insertions: number,
	/**  Total deleted lines across this side. */
	deletions: number,
};

/**  File text and metadata read from one worktree revision. */
export type WorktreeFileContent = {
	/**  Side from which the file was read. */
	side: WorktreeSide,
	/**  Revision from which the file was read. */
	revision: string,
	/**  Repository-relative file path. */
	path: string,
	/**  Number of text lines, when available. */
	lines: number,
	/**  File size in bytes represented as decimal text. */
	bytes: string,
	/**  Why text was omitted, if applicable. */
	omitted: DiffOmission | null,
	/**  File text, or `None` when omitted. */
	text: string | null,
};

/**  Reads a local file from the index or disk. */
export type WorktreeFileContentRequest = {
	/**  Side containing the requested file. */
	side: WorktreeSide,
	/**  Repository-relative file path. */
	path: string,
	/**  Revision token from the snapshot used to select the file. */
	expected_revision: string | null,
	/**  Whether to bypass the ordinary content-size limit. */
	expand: boolean,
};

/**  One selected worktree file diff tied to its source revision. */
export type WorktreeFileDiff = {
	/**  Side containing the file. */
	side: WorktreeSide,
	/**  Revision from which the patch was read. */
	revision: string,
	/**  File summary and selected patch. */
	file: FileDiff,
};

/**  A single detailed local diff, fetched after a file is selected. */
export type WorktreeFileDiffRequest = {
	/**  Side containing the requested file. */
	side: WorktreeSide,
	/**  Repository-relative file path. */
	path: string,
	/**  Revision token from the snapshot used to select the file. */
	expected_revision: string | null,
	/**  Whether to bypass the ordinary patch-size limit. */
	expand: boolean,
};

/**  Lightweight revision used by the fallback poller and stale-read guard. */
export type WorktreeFingerprint = {
	/**  Compact revision token for the current local changes. */
	revision: string,
};

/**  Which side of the local changes the caller wants to inspect. */
export type WorktreeSide =
/**  Changes already staged in the index. */
"staged" |
/**  Changes in the working directory that are not staged. */
"unstaged";

/**  Both sides share one revision and one React Query cache entry. */
export type WorktreeSnapshot = {
	/**  Revision token that identifies both sides of this snapshot. */
	revision: string,
	/**  Staged changes at this revision. */
	staged: WorktreeDiffPage,
	/**  Unstaged changes at this revision. */
	unstaged: WorktreeDiffPage,
};

/**  The combined initial snapshot request. */
export type WorktreeSnapshotRequest = {
	/**  Staged-side cursor, if requesting a later page. */
	staged_cursor: string | null,
	/**  Unstaged-side cursor, if requesting a later page. */
	unstaged_cursor: string | null,
	/**  Maximum number of files to return, or `None` for the default. */
	limit: number | null,
	/**  Revision that must still be current for a paged read. */
	expected_revision: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}
