// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Round-trips the IPC boundary and reports what is running.
	 * 
	 *  This exists to prove the whole pipeline — command registration, type
	 *  generation, and the TypeScript client — works end to end before anything
	 *  depends on it.
	 */
	ping: () => __TAURI_INVOKE<AppInfo>("ping"),
	/**  Validates and opens a local repository, returning its canonical identity. */
	openRepository: (path: string) => typedError<RepositoryInfo, AppError>(__TAURI_INVOKE("open_repository", { path })),
	/**  Checks a candidate working-tree root without changing application selection. */
	validateRepository: (path: string) => typedError<RepositoryInfo, AppError>(__TAURI_INVOKE("validate_repository", { path })),
	/**
	 *  The repository named on the command line, if the application was launched
	 *  with one.
	 * 
	 *  `gitcanvas /path/to/repo` is what a terminal user expects of a Git client,
	 *  and it is also what lets the end-to-end suite open a repository without a
	 *  native file dialog. Validated here, so an unusable argument surfaces as a
	 *  normal error rather than a window that silently opens on nothing.
	 */
	getStartupRepository: () => typedError<{
	path: string,
	name: string,
} | null, AppError>(__TAURI_INVOKE("get_startup_repository")),
	/**  Reads a bounded history page using the selected repository's canonical path. */
	getCommits: (path: string, request: HistoryRequest) => typedError<HistoryPage, AppError>(__TAURI_INVOKE("get_commits", { path, request })),
	/**  Lists local and remote branches and identifies the current branch. */
	getBranches: (path: string) => typedError<BranchInfo[], AppError>(__TAURI_INVOKE("get_branches", { path })),
	/**  Lists tags, peeling annotated tags to commits when applicable. */
	getTags: (path: string) => typedError<TagInfo[], AppError>(__TAURI_INVOKE("get_tags", { path })),
	/**
	 *  Reads a commit's changes against its first parent.
	 * 
	 *  `request.expand_path` opts one file out of the size guard, which is how the
	 *  interface loads a large diff only when the user asks for it.
	 */
	getCommitDiff: (path: string, request: DiffRequest) => typedError<CommitDiff, AppError>(__TAURI_INVOKE("get_commit_diff", { path, request })),
	/**  Stores a personal access token in the OS keychain. */
	storeGithubToken: (token: string) => typedError<GitHubAccount, AppError>(__TAURI_INVOKE("store_github_token", { token })),
	/**  Reports whether a token is stored, without revealing it. */
	hasGithubToken: () => typedError<boolean, AppError>(__TAURI_INVOKE("has_github_token")),
	/**  Removes the stored token. */
	forgetGithubToken: () => typedError<null, AppError>(__TAURI_INVOKE("forget_github_token")),
	/**  Lists the repositories the stored token can reach. */
	listGithubRepositories: () => typedError<GitHubRepository[], AppError>(__TAURI_INVOKE("list_github_repositories")),
	/**  Clones a repository into the application cache, emitting progress as it goes. */
	cloneGithubRepository: (cloneUrl: string, fullName: string) => typedError<ClonedRepository, AppError>(__TAURI_INVOKE("clone_github_repository", { cloneUrl, fullName })),
	/**  Reports what the clone cache holds and the limits it is held to. */
	getCloneCacheStatus: () => typedError<CacheStatus, AppError>(__TAURI_INVOKE("get_clone_cache_status")),
	/**  Checks out a local branch, refusing by default when work would be lost. */
	checkoutBranch: (path: string, branch: string, force: boolean) => typedError<CheckoutOutcome, AppError>(__TAURI_INVOKE("checkout_branch", { path, branch, force })),
	/**  Fetches and fast-forwards the current branch, reporting anything else. */
	pullFastForward: (path: string) => typedError<PullOutcome, AppError>(__TAURI_INVOKE("pull_fast_forward", { path })),
	/**  Pushes the current branch to its remote. */
	pushCurrentBranch: (path: string) => typedError<PushOutcome, AppError>(__TAURI_INVOKE("push_current_branch", { path })),
};

/** Events */
export const events = {
	cloneProgressEvent: makeEvent<CloneProgressEvent>("clone-progress-event"),
};

/* Types */
/**  A domain failure, never a raw library error or a panic. */
export type AppError = 
/**  The supplied path does not identify a supported working repository. */
{ kind: "InvalidRepository"; message: string } | 
/**  A filesystem operation failed. */
{ kind: "Io"; message: string } | 
/**  libgit2 could not complete an operation. */
{ kind: "Git"; message: string } | 
/**  A request violates the public contract. */
{ kind: "InvalidInput"; message: string } | 
/**  The history represented by a pagination cursor is no longer available. */
{ kind: "StaleCursor"; message: string } | 
/**  Background work could not complete. */
{ kind: "Internal"; message: string };

/**
 *  What the application reports about itself.
 * 
 *  Deliberately a struct rather than a bare string: it exercises struct
 *  generation through specta, which is the shape every real payload will take.
 */
export type AppInfo = {
	/**  Display name of the application. */
	name: string,
	/**  Version of the Tauri application shell. */
	version: string,
	/**  Version of the git engine crate backing it. */
	core_version: string,
};

/**  A branch uses its full ref name as identity; short names are display only. */
export type BranchInfo = {
	name: string,
	full_name: string,
	target: string,
	is_remote: boolean,
	is_head: boolean,
	is_symbolic: boolean,
};

/**  One cached clone. */
export type CacheEntry = {
	path: string,
	name: string,
	/**
	 *  Size in bytes, as a decimal string.
	 * 
	 *  A directory can exceed what a JavaScript number represents exactly, and
	 *  specta refuses to export 64-bit integers for that reason. The same
	 *  convention as commit timestamps: cross the boundary as text, parse on
	 *  the far side.
	 */
	bytes: string,
	/**  Unix seconds of the most recent access, as a string for range safety. */
	last_used: string,
};

/**  What the cache currently holds. */
export type CacheStatus = {
	entries: CacheEntry[],
	/**  Total size in bytes, as a decimal string. See [`CacheEntry::bytes`]. */
	total_bytes: string,
	max_repositories: number,
	/**  Limit in bytes, as a decimal string. See [`CacheEntry::bytes`]. */
	max_total_bytes: string,
};

/**
 *  The outcome of a checkout attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type CheckoutOutcome = 
/**  The branch is now checked out. */
{ kind: "Switched"; branch: string } | 
/**  Refused: these changes would have been lost. */
{ kind: "Blocked"; conflicts: DirtyPath[] };

/**  Progress for an in-flight clone, emitted as it advances. */
export type CloneProgressEvent = {
	full_name: string,
	received_objects: number,
	total_objects: number,
	received_bytes: string,
};

/**  Where a clone landed. */
export type ClonedRepository = {
	path: string,
	full_name: string,
};

/**  A commit's changes against its first parent. */
export type CommitDiff = {
	commit_id: string,
	/**  The parent compared against; absent for a root commit. */
	parent_id: string | null,
	files: FileDiff[],
	insertions: number,
	deletions: number,
	/**  True when this commit has more than one parent, so the diff covers one side. */
	is_merge: boolean,
};

/**  One commit in the graph. Times are decimal Unix seconds, preserving Git's full integer range. */
export type CommitInfo = {
	id: string,
	parents: string[],
	summary: string,
	message: string,
	author_name: string,
	author_email: string,
	author_time: string,
	commit_time: string,
};

/**  Why a file has no renderable hunks. */
export type DiffOmission = 
/**  libgit2 reports the content as binary; there is no line diff to show. */
"Binary" | 
/**  The change is larger than `LARGE_DIFF_LINE_LIMIT` and was not requested. */
"TooLarge";

/**  Which file, if any, the caller wants in full regardless of its size. */
export type DiffRequest = {
	commit_id: string,
	/**  Path to include in full even if it exceeds the size guard. */
	expand_path: string | null,
};

/**  A path that would be lost or overwritten by an operation. */
export type DirtyPath = {
	path: string,
	/**  True when the change is staged, false when it is only in the worktree. */
	staged: boolean,
};

/**  How a path changed between two trees. */
export type FileChange = "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "TypeChanged" | "Other";

/**
 *  One file in a commit's diff.
 * 
 *  `patch` is `None` whenever `omitted` is set, so the two can never disagree
 *  about whether there is something to render.
 */
export type FileDiff = {
	path: string,
	/**  Previous path for renames and copies. */
	old_path: string | null,
	change: FileChange,
	insertions: number,
	deletions: number,
	omitted: DiffOmission | null,
	/**  Unified patch text for this file alone, ready for a diff renderer. */
	patch: string | null,
};

/**  The authenticated account. */
export type GitHubAccount = {
	login: string,
	name: string | null,
};

/**  A repository the token can reach. */
export type GitHubRepository = {
	full_name: string,
	clone_url: string,
	private: boolean,
	default_branch: string,
	description: string | null,
};

/**  A bounded page and the information needed to resume its exact traversal. */
export type HistoryPage = {
	commits: CommitInfo[],
	next_cursor: string | null,
	roots: string[],
};

/**  Request for a page. Continuations carry the prior page's immutable walk roots. */
export type HistoryRequest = {
	limit: number,
	cursor: string | null,
	roots: string[] | null,
};

/**
 *  The outcome of a pull attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type PullOutcome = 
/**  Already up to date; nothing was fetched that changes the branch. */
{ kind: "UpToDate" } | 
/**  Fast-forwarded to the remote tip. */
{ kind: "FastForwarded"; commits: number; to: string } | 
/**  Refused: the histories diverged and a real merge would be required. */
{ kind: "DivergedRequiresMerge"; local: string; remote: string } | 
/**  The branch has no upstream to pull from. */
{ kind: "NoUpstream" };

/**
 *  The outcome of a push attempt.
 *  Serialized with an internal `kind` tag so TypeScript sees a discriminated
 *  union it can narrow with a `switch`, matching how `AppError` already
 *  crosses the boundary. The default external tagging generates a shape that
 *  needs a key lookup before anything can be read.
 */
export type PushOutcome = { kind: "Pushed"; branch: string; remote: string } | 
/**  Refused: the remote has commits the local branch does not. */
{ kind: "RejectedNonFastForward"; branch: string };

/**  Displayable repository identity, safe to send across IPC. */
export type RepositoryInfo = {
	path: string,
	name: string,
};

/**  A tag may refer to any Git object, so a commit target is explicitly optional. */
export type TagInfo = {
	name: string,
	target: string,
	commit_id: string | null,
	is_annotated: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

