// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Round-trips the IPC boundary and reports what is running.
	 * 
	 *  This exists to prove the whole pipeline — command registration, type
	 *  generation, and the TypeScript client — works end to end before anything
	 *  depends on it.
	 */
	ping: () => __TAURI_INVOKE<AppInfo>("ping"),
};

/* Types */
/**
 *  What the application reports about itself.
 * 
 *  Deliberately a struct rather than a bare string: it exercises struct
 *  generation through specta, which is the shape every real payload will take.
 */
export type AppInfo = {
	/**  Display name of the application. */
	name: string,
	/**  Version of the Tauri application shell. */
	version: string,
	/**  Version of the git engine crate backing it. */
	core_version: string,
};

